version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${MYSQL_USER}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${PORT}:${PORT}'
    expose:
      # Opens port 3306 on the container
      - '${PORT}'
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    depends_on:
      - db
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./src:/app/src  # Mounting the src directory as a volume for nodemon

volumes:
  my-db:
